const About = () => {
  return (
    <div style={{margin:50}}>
      <h1 style={{ textAlign:"center" }}>Le crépuscule du soir</h1>

      Le jour tombe. Un grand apaisement se fait dans les pauvres esprits fatigués du labeur de la journée; et leurs pensées prennent maintenant les couleurs tendres et indécises du crépuscule. Cependant du haut de la montagne arrive à mon balcon, à travers les nues transparentes du soir, un grand hurlement, composé d'une foule de cris discordants, que l'espace transforme en une lugubre harmonie, comme celle de la marée qui monte ou d'une tempête qui s'éveille.
      Quels sont les infortunés que le soir ne calme pas, et qui prennent, comme les hiboux, la venue de la nuit pour un signal de sabbat? Cette sinistre ululation nous arrive du noir hospice perché sur la montagne, et, le soir, en fumant et en contemplant le repos de l'immense vallée, hérissée de maisons dont chaque fenêtre dit: "C'est ici la paix maintenant; c'est ici la joie de la famille!" je puis, quand le vent souffle de là-haut, bercer ma pensée étonnée à cette imitation des harmonies de l'enfer.
      Le crépuscule excite les fous. -- Je me souviens que j'ai eu deux amis que le crépuscule rendait tout malades. L'un méconnaissait alors tous les rapports d'amitié et de politesse, et maltraitait, comme un sauvage, le premier venu. Je l'ai vu jeter à la tête d'un maître d'hôtel un excellent poulet, dans lequel il croyait voir je ne sais quel insultant hiéroglyphe. Le soir, précurseur des voluptés profondes, lui gâtait les choses les plus succulentes.
      L'autre, un ambitieux blessé, devenait, à mesure que le jour baissait, plus aigre, plus sombre, plus taquin. Indulgent et sociable encore pendant la journée, il était impitoyable le soir; et ce n'était pas seulement sur autrui, mais aussi sur lui-même que s'exerçait rageusement sa manie crépusculeuse.
      Le premier est mort fou, incapable de reconnaître sa femme et son enfant; le second porte en lui l'inquiétude d'un malaise perpétuel, et fût-il gratifié de tous les honneurs que peuvent conférer les républiques et les princes, je crois que le crépuscule allumerait encore en lui la brûlante envie de distinctions imaginaires. La nuit, qui mettait ses ténèbres dans leur esprit, fait la lumière dans le mien; et, bien qu'il ne soit pas rare de voir la même cause engendrer deux effets contraires, j'en suis toujours comme intrigué et alarmé.
      O nuit! ô rafraîchissantes ténèbres! vous êtes pour moi le signal d'une fête intérieure, vous êtes la délivrance d'une angoisse! Dans la solitude des plaines, dans les labyrinthes pierreux d'une capitale, scintillement des étoiles, explosion des lanternes, vous êtes le feu d'artifice de la déesse Liberté!
      Crépuscule, comme vous êtes doux et tendre! Les lueurs roses qui traînent encore à l'horizon comme l'agonie du jour sous l'oppression victorieuse de sa nuit, les feux des candélabres qui font des taches d'un rouge opaque sur les dernières gloires du couchant, les lourdes draperies qu'une main invisible attire des profondeurs de l'Orient, imitent tous les sentiments compliqués qui luttent dans le coeur de l'homme aux heures solennelles de la vie.
      On dirait encore une de ces robes étranges de danseuses, où une gaze- transparente et sombre laisse entrevoir les splendeurs amorties d'une jupe éclatante, comme sous le noir présent transperce le délicieux passé; et les étoiles vacillantes d'or et d'argent, dont elle est semée, représentent ces feux de la fantaisie qui ne s'allument bien que sous le deuil profond de la Nuit.
    </div>
  )
}

export default About
